title: Blain Allen Blanchard
description: This is a test of the new site.
show_downloads: true

baseurl: "/Stark" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://bab223.github.io/Stark" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%A, %B %d, %Y"

theme: # leave it empty

# social
author: "Blain Blanchard"
image: /thumbnail-jumbo.png
twitter:
  username: xblainx
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: Blain Blanchard
#  admins:
